spring:
  application:
    name=FakeCommerce
  datasource:
    url: jdbc:mysql://localhost:3306/fakecommerce
    username: ${USERNAME}
    password : ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
